name: Publish

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PTA }}

      - name: Git set author name
        run: git config --global user.name "runespoorengineering"

      - name: Git set author email
        run: git config --global user.email "runespoorengineering@gmail.com"

      - name: Use Node.js/20.9.0
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ secrets.NPM_REGISTRY_URL }}
          always-auth: true
          node-version: 20.9.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}

      - name: Publish
        run: pnpm publish --access public --no-git-checks
